### PR TITLE
Database performance audit

### PR DESCRIPTION
**Pull request by MostafaShahat2021**
## In this PR:
-⭐️Added email as an extra column to the owner's table.
-⭐️ Inserted given data

##Queries:
SELECT COUNT(*) FROM visits where animal_id = 4;

Before:  
Screenshot from 2023-11-02 12-50-28

After indexing:
⭐️Saved > 600 ms of execution time
Screenshot from 2023-11-02 13-03-12

SELECT * FROM visits where vet_id = 2;

Before:
Screenshot from 2023-11-02 12-51-11

After indexing:
⭐️Saved > 200 ms of execution time
Screenshot from 2023-11-02 16-38-16

SELECT * FROM owners where email = 'owner_18327@mail.com';

Before:
Screenshot from 2023-11-02 12-51-37

After indexing:
⭐️Saved > 1400 ms of execution time
Screenshot from 2023-11-02 16-39-27

### CODE REVIEW

**Review by zeff96 — APPROVED** [review]
### Status: APPROVED :green_circle: 
Hi @MostafaShahat2021 and @Titus-Kiplagat , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

congrats

## Highlights
:heavy_check_mark: Correct GitFlow
:heavy_check_mark: All indices created
:heavy_check_mark: Professional and clear screenshots
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MostafaShahat2021** [comment]
Hey @zeff96, Thanks a lot 💯 for your efforts in reviewing our code 😄

**Comment by zeff96** [comment]
@MostafaShahat2021, Long time, how are you doing in the program

**Comment by MostafaShahat2021** [comment]
I'm doing great, I'm so happy that you gave me the code review 😄, wish you all the best brother 👍

**Comment by zeff96** [comment]
@MostafaShahat2021, Wish you all the best too

**Pull request merged**
